[options]
HoldPkg      = pacman glibc
Architecture = auto
CheckSpace
ParallelDownloads = 5
CacheDir     = /home/darthmike/Documents/web_personal/archspeech/pkg-cache/
CacheDir     = /var/cache/pacman/pkg/
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[community]
Include = /etc/pacman.d/mirrorlist
